/**
 * 错误码注册表 - 后端返回给前端的稳定错误标识。
 *
 * 规范: MODULE_SEMANTIC(大写蛇形),如 AUTH_INVALID_CREDENTIALS。
 * 新增错误码时需三处同步:
 *   1. 本枚举
 *   2. 前端三语词条 src/i18n/{zh,en,ja}.json 的 errors 命名空间
 *   3. 代码审查约束
 */
export enum ErrorCode {
  // ===== 通用 =====
  INTERNAL = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',

  // ===== AUTH 认证 =====
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_CODE = 'AUTH_INVALID_CODE',
  AUTH_CODE_REQUIRED = 'AUTH_CODE_REQUIRED',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_RESET_LINK_INVALID = 'AUTH_RESET_LINK_INVALID',
  AUTH_EMAIL_REQUIRED = 'AUTH_EMAIL_REQUIRED',
  AUTH_EMAIL_TAKEN = 'AUTH_EMAIL_TAKEN',

  // ===== USER 用户 =====
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  USER_LAST_ADMIN_REMOVE = 'USER_LAST_ADMIN_REMOVE',
  USER_LAST_ADMIN_DISABLE = 'USER_LAST_ADMIN_DISABLE',
  USER_LAST_ADMIN_DELETE = 'USER_LAST_ADMIN_DELETE',
  USER_PERMISSION_DENIED = 'USER_PERMISSION_DENIED',
  USER_APPLICATION_INVALID = 'USER_APPLICATION_INVALID',
  USER_APPLICATION_PENDING = 'USER_APPLICATION_PENDING',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // ===== ASSET / STORAGE 资产与存储 =====
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  ASSET_UPLOAD_FAILED = 'ASSET_UPLOAD_FAILED',
  STORAGE_KEY_MISSING = 'STORAGE_KEY_MISSING',
  STORAGE_BODY_EMPTY = 'STORAGE_BODY_EMPTY',
  STORAGE_AUTH_REQUIRED = 'STORAGE_AUTH_REQUIRED',
  STORAGE_SESSION_EXPIRED = 'STORAGE_SESSION_EXPIRED',
  STORAGE_FILE_NOT_FOUND = 'STORAGE_FILE_NOT_FOUND',

  // ===== CHANNEL 渠道 =====
  CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
  CHANNEL_UNAVAILABLE = 'CHANNEL_UNAVAILABLE',
  CHANNEL_KEY_DECRYPT_FAILED = 'CHANNEL_KEY_DECRYPT_FAILED',
  CHANNEL_KEY_MISSING = 'CHANNEL_KEY_MISSING',
  CHANNEL_BASE_URL_MISSING = 'CHANNEL_BASE_URL_MISSING',

  // ===== AI 生成 / 思考 =====
  AI_LLM_CONNECTION_FAILED = 'AI_LLM_CONNECTION_FAILED',
  AI_LLM_CALL_FAILED = 'AI_LLM_CALL_FAILED',
  AI_LLM_STREAM_UNREADABLE = 'AI_LLM_STREAM_UNREADABLE',
  AI_GENERATION_FAILED = 'AI_GENERATION_FAILED',
  AI_GENERATION_TIMEOUT = 'AI_GENERATION_TIMEOUT',
  AI_GENERATION_NOT_FOUND = 'AI_GENERATION_NOT_FOUND',
  AI_THINK_FAILED = 'AI_THINK_FAILED',
  AI_THINK_EMPTY = 'AI_THINK_EMPTY',
  THINK_TASK_NOT_FOUND = 'THINK_TASK_NOT_FOUND',
  THINK_CANCELLED = 'THINK_CANCELLED',
  THINK_TERMINATED = 'THINK_TERMINATED',
  THINK_CHUNKING_PROGRESS = 'THINK_CHUNKING_PROGRESS',

  // ===== PROJECT / COLLAB 项目与协作 =====
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_PERMISSION_DENIED = 'PROJECT_PERMISSION_DENIED',
  COLLAB_ROOM_NOT_FOUND = 'COLLAB_ROOM_NOT_FOUND',
  COLLAB_ROOM_EXISTS = 'COLLAB_ROOM_EXISTS',
  COLLAB_ROOM_FULL = 'COLLAB_ROOM_FULL',
  COLLAB_ROOM_OWNER_REQUIRED = 'COLLAB_ROOM_OWNER_REQUIRED',
  COLLAB_INVITE_INVALID = 'COLLAB_INVITE_INVALID',
  COLLAB_MEMBER_BANNED = 'COLLAB_MEMBER_BANNED',
  COLLAB_MEMBER_MUTED = 'COLLAB_MEMBER_MUTED',
  COLLAB_DEVICE_LIMIT = 'COLLAB_DEVICE_LIMIT',
  COLLAB_APPLICATION_NOT_FOUND = 'COLLAB_APPLICATION_NOT_FOUND',

  // ===== POLICY / PRICING / PROMPT 政策与提示词 =====
  POLICY_NOT_FOUND = 'POLICY_NOT_FOUND',
  POLICY_VERSION_NOT_FOUND = 'POLICY_VERSION_NOT_FOUND',
  POLICY_PUBLISHED_LOCKED = 'POLICY_PUBLISHED_LOCKED',
  PRICING_CHANNEL_NOT_FOUND = 'PRICING_CHANNEL_NOT_FOUND',
  PROMPT_NOT_FOUND = 'PROMPT_NOT_FOUND',
  PROMPT_FAVORITE_NOT_FOUND = 'PROMPT_FAVORITE_NOT_FOUND',

  // ===== BILLING / 其它 =====
  CREDIT_INSUFFICIENT = 'CREDIT_INSUFFICIENT',
  SCRIPT_NOT_FOUND = 'SCRIPT_NOT_FOUND',
  FOLDER_NOT_FOUND = 'FOLDER_NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
}
